version: '3'

services:
  client-service:
    build: ./client
    volumes:
      - ./client/src:/var/www/html/
    ports:
      - 5001:80
    depends_on:
      - api-service

  api-service:
    build: ./api
    volumes:
      - ./api/src:/var/www/html/
    ports:
      - 5002:80
